[mypy]
python_version = 3.10
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True

[mypy-llm.*]
ignore_missing_imports = True
[mypy-sandbox.*]
ignore_missing_imports = True

[mypy-shell.*]
ignore_missing_imports = True

[mypy-prompt_builder.*]
ignore_missing_imports = True
